<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array/>
    <key>foldingStartMarker</key>
    <string>(&lt;(?i:(head|table|tr|div|style|script|ul|ol|form|dl))\b.*?&gt;|{% (block|comment|filter|for|if|ifchanged|ifequal|ifnotequal))</string>
    <key>foldingStopMarker</key>
    <string>(&lt;/(?i:(head|table|tr|div|style|script|ul|ol|form|dl))&gt;|{% (endblock|endblocktrans|endcomment|endfilter|endfor|endif|endifchanged|endifequal|endifnotequal) %})</string>
    <key>keyEquivalent</key>
    <string>^~H</string>
    <key>name</key>
    <string>HTML (Django)</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>comment</key>
            <string>Since html is valid in Django templates include the html patterns</string>
            <key>include</key>
            <string>text.html.basic</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>{% comment %}</string>
            <key>end</key>
            <string>{% endcomment %}</string>
            <key>name</key>
            <string>comment.block.django.template</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>{#</string>
            <key>end</key>
            <string>#}</string>
            <key>name</key>
            <string>comment.line.django.template</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>{{</string>
            <key>end</key>
            <string>}}</string>
            <key>name</key>
            <string>variable.other.django.template</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#expression</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>({%)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.other.django.tagbraces</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(%})</string>
            <key>name</key>
            <string>meta.scope.django.template.tag</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(autoescape|endautoescape|block|endblock|blocktrans|endblocktrans|plural|debug|extends|filter|firstof|for|endfilter|endfor|if|include|else|endif|empty|ifchanged|endifchanged|ifequal|endifequal|ifnotequal|endifnotequal|from|import|load|macro|now|regroup|ssi|set|spaceless|endspaceless|endcapture|templatetag|widthratio|with|endwith)\b</string>
                    <key>name</key>
                    <string>keyword.control.django.template</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(and|or|not|in|by|as)\b</string>
                    <key>name</key>
                    <string>keyword.operator.django.template</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\|(add|addslashes|capfirst|center|cut|date|default|default_if_none|dictsort|dictsortreversed|divisibleby|escape|filesizeformat|first|fix_ampersands|floatformat|get_digit|join|length|length_is|linebreaks|linebreaksbr|linenumbers|ljust|lower|make_list|phone2numeric|pluralize|pprint|random|removetags|rjust|safe|slice|slugify|stringformat|striptags|time|timesince|title|truncatewords|unordered_list|upper|urlencode|urlize|urlizetrunc|wordcount|wordwrap|yesno)\b</string>
                    <key>name</key>
                    <string>support.function.filter.django</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>'|"</string>
                    <key>end</key>
                    <string>'|"</string>
                    <key>name</key>
                    <string>string.other.django.template.tag</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>[a-zA-Z_]+</string>
                    <key>name</key>
                    <string>string.unquoted.django.template.tag</string>
                </dict>
            </array>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>escaped_char</key>
        <dict>
            <key>match</key>
            <string>\\x[0-9A-F]{2}</string>
            <key>name</key>
            <string>constant.character.escape.hex.django</string>
        </dict>
        <key>escaped_unicode_char</key>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.unicode.16-bit-hex.django</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.unicode.32-bit-hex.django</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.unicode.name.django</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(\\U[0-9A-Fa-f]{8})|(\\u[0-9A-Fa-f]{4})|(\\N\{[a-zA-Z ]+\})</string>
        </dict>
        <key>expression</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.control.django</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.django.block</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>\s*\b(block)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.control.django</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.django.filter</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>\s*\b(filter)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.control.django</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.django.test</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>\s*\b(is)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.control.django</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;=\{\%-|\{\%)\s*\b([a-zA-Z_][a-zA-Z0-9_]*)\b(?!\s*[,=])</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(and|else|if|in|import|not|or|recursive|with(out)?\s+context)\b</string>
                    <key>name</key>
                    <string>keyword.control.django</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(true|false|none)\b</string>
                    <key>name</key>
                    <string>constant.language.django</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(loop|super|self|varargs|kwargs)\b</string>
                    <key>name</key>
                    <string>variable.language.django</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>[a-zA-Z_][a-zA-Z0-9_]*</string>
                    <key>name</key>
                    <string>variable.other.django</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\+|\-|\*\*|\*|//|/|%)</string>
                    <key>name</key>
                    <string>keyword.operator.arithmetic.django</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.other.django</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.django.filter</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(\|)([a-zA-Z_][a-zA-Z0-9_]*)</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.other.django</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.django.attribute</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(\.)([a-zA-Z_][a-zA-Z0-9_]*)</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>\[</string>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.other.django</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\]</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#expression</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>\(</string>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.other.django</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#expression</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>\{</string>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.other.django</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\}</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#expression</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\.|:|\||,)</string>
                    <key>name</key>
                    <string>punctuation.other.django</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(==|&lt;=|=&gt;|&lt;|&gt;|!=)</string>
                    <key>name</key>
                    <string>keyword.operator.comparison.django</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>=</string>
                    <key>name</key>
                    <string>keyword.operator.assignment.django</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>"</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.django</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>"</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.django</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>string.quoted.double.django</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#string</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>'</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.django</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>'</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.django</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>string.quoted.single.django</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#string</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>@/</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.regexp.begin.django</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>/</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.regexp.end.django</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>string.regexp.django</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#simple_escapes</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>simple_escapes</key>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.newline.django</string>
                </dict>
                <key>10</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.tab.django</string>
                </dict>
                <key>11</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.vertical-tab.django</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.backlash.django</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.double-quote.django</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.single-quote.django</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.bell.django</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.backspace.django</string>
                </dict>
                <key>7</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.formfeed.django</string>
                </dict>
                <key>8</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.linefeed.django</string>
                </dict>
                <key>9</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.return.django</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(\\\n)|(\\\\)|(\\\")|(\\')|(\\a)|(\\b)|(\\f)|(\\n)|(\\r)|(\\t)|(\\v)</string>
        </dict>
        <key>string</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#simple_escapes</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#escaped_char</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#escaped_unicode_char</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>text.html.django</string>
    <key>uuid</key>
    <string>F4B0A70C-ECF6-4660-BC26-785216E3CF02</string>
</dict>
</plist>
